### ISSUE TITLE
var.set broken in version 0.15.4

### ISSUE THREAD

**Issue by IgorSimic** [snarky-snark/home-assistant-variables#115]
Following:
service: var.set
data:
  entity_id: var.hass_up
  value: "on"

works without any problem in version 0.15.3
but in version 0.15.4 produces error:
Traceback (most recent call last):
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hass312/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/var/__init__.py", line 447, in async_set
    await self.async_write_ha_state()
TypeError: object NoneType can't be used in 'await' expression

**Comment by snarky-snark** [comment]
Is v0.15.5 any better?

**Comment by IgorSimic** [comment]
Yes, it works now. Thank you very much.
