### ISSUE TITLE
Reserved words?

### ISSUE THREAD

**Issue by ijustlikeit** [snarky-snark/home-assistant-variables#19]
Couldn't set up variables called "Armed" nor "Disarmed".  There must be some reserved words that cannot be used??

**Comment by snarky-snark** [comment]
Post your config and version. There are no reserved words in this component.

**Comment by ijustlikeit** [comment]
The config file--->
var:
  Armed:
     friendly_name: "Armed"
     initial_value: 'Armed'
     icon: mdi:alarm-bell
  Disarmed:
     friendly_name: "Disarmed"
     initial_value: 'Disarmed'
     icon: mdi:bell-off
    
and the error msg:

Invalid config for [var]: [Armed] is an invalid option for [var]. Check: var->var->Armed. (See /config/configuration.yaml, line 23). Please check the docs at https://home-assistant.io/integrations/var/

**Comment by snarky-snark** [comment]
You have to use proper indentation. Also try using all lowercase.

**Comment by ijustlikeit** [comment]
I have proper indentation..the copy paste removed it.

**Comment by ijustlikeit** [comment]
Throws up a whole bunch of error messages:
2020-01-12 12:11:37 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-12 12:11:43 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 218, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 231, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 278, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 920, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 699, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 653, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by snarky-snark** [comment]
Which version of Home Assistant are you running?

**Comment by snarky-snark** [comment]
That error is noted in #6 and shouldn't affect the operation of the component.

**Comment by ijustlikeit** [comment]
The latest one Home Assistant 0.103.6.
I'm just removing this "var;" integration for now.  I have other ways of doing this.  Thanks.
